"""Shared data models for the momentum strategy layer."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Literal


@dataclass
class Candle:
    """OHLCV candle with optional buy/sell volume split."""

    timestamp: int  # epoch ms
    open: float
    high: float
    low: float
    close: float
    volume: float  # USD notional
    trades: int  # trade count
    buy_volume: float = 0.0
    sell_volume: float = 0.0


class SignalDirection(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"


class OrderType(str, Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"


class ExitReason(str, Enum):
    STOP_LOSS = "STOP_LOSS"
    TAKE_PROFIT = "TAKE_PROFIT"
    TRAILING_STOP = "TRAILING_STOP"
    TIMEOUT = "TIMEOUT"
    MANUAL = "MANUAL"
    RISK_LIMIT = "RISK_LIMIT"


class PositionStatus(str, Enum):
    PENDING = "PENDING"
    OPEN = "OPEN"
    CLOSED = "CLOSED"


@dataclass
class Signal:
    """A trading signal generated by the strategy engine."""

    coin: str
    direction: SignalDirection
    entry_price: float
    stop_loss: float
    take_profit: float
    regime_score: int  # 0-5 composite regime quality
    timestamp: int  # epoch ms when signal was generated
    rr_ratio: float = 0.0  # reward-to-risk ratio
    staircase_score: float = 0.0
    volume_score: float = 0.0
    confidence: float = 0.0  # 0-100 composite confidence
    order_type: OrderType = OrderType.MARKET  # limit vs market
    # CVD / orderbook quality signals (populated by pipeline if available)
    cvd_confirming: bool | None = None  # CVD direction matches trade direction
    cvd_divergent: bool = False         # CVD diverging from price
    orderbook_imbalance: float = 0.0    # -1 to +1, positive = bullish
    aggressor_ratio: float = 1.0        # buy_vol / sell_vol (5m window)

    def __post_init__(self) -> None:
        risk = abs(self.entry_price - self.stop_loss)
        reward = abs(self.take_profit - self.entry_price)
        self.rr_ratio = reward / risk if risk > 0 else 0.0


@dataclass
class ManagedPosition:
    """A position being actively managed by the bot."""

    coin: str
    direction: SignalDirection
    entry_price: float
    size: float  # in asset units
    notional_usd: float
    stop_loss: float
    take_profit: float
    trailing_stop: float | None = None
    status: PositionStatus = PositionStatus.OPEN
    entry_time: int = 0  # epoch ms
    exit_time: int = 0  # epoch ms
    exit_price: float = 0.0
    exit_reason: ExitReason | None = None
    highest_price: float = 0.0  # for trailing stop (long)
    lowest_price: float = float("inf")  # for trailing stop (short)
    signal: Signal | None = None
    pnl: float = 0.0
    pnl_pct: float = 0.0
    leverage: int = 1
    tags: list[str] = field(default_factory=list)

    @property
    def is_long(self) -> bool:
        return self.direction == SignalDirection.LONG

    @property
    def unrealized_pnl(self) -> float:
        """Calculate unrealized PnL given the current highest/lowest tracked price."""
        if self.status == PositionStatus.CLOSED:
            return self.pnl
        ref_price = self.highest_price if self.is_long else self.lowest_price
        if self.is_long:
            return (ref_price - self.entry_price) * self.size
        return (self.entry_price - ref_price) * self.size
